name: 'PR Build Check (Python + Docker)'
description: 'Checks if the build succeeds for a PR, including Python script execution and Docker build.'

inputs:
  github_token:
    description: 'GitHub Token to authenticate API requests (required)'
    required: true
  codeowners_file:
    description: 'Path to the CODEOWNERS file (default: .github/CODEOWNERS)'
    required: false
    default: '.github/CODEOWNERS'
  pr_number:
    description: 'Pull request number (default: event PR number)'
    required: false
  min_approval:
    description: 'Minimum number of approvals required for PR (default: 1)'
    required: false
    default: 1

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'blue'