name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Verify CODEOWNERS Approval
        uses: ./.github/actions/verify-codeowners
        with:
          github_token: "MOCK_GITHUB_TOKEN"  # Use a dummy token for testing
          codeowners_file: ".github/CODEOWNERS"
          pr_number: ${{ github.event.pull_request.number }}
          min_approval: 1

      - name: Run build/test
        run: |
          python src/main.py